title: Md. Monir Hossain # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Wordpress Developer with a demonstrated history of working in the WordPress Theme & Plugin Development. Skilled in PHP, jQuery, JavaScript, WordPress, WordPress Design, Content Management Systems (CMS), WooCommerce and Research. Strong engineering professional with a Bachelor of Engineering focused on Computer Science from Bangladesh University of Business and Technology. 
  <br><br>
  <a href="mailto:fencemonir@gmail.com">Mail Me</a>
  <br><br>
  <a href="https://www.linkedin.com/in/monir-hossain-81766686/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal

